### ISSUE TITLE
Caching local plugin repo data prevents use of locally stored packages when used in back to back updates

### ISSUE THREAD

**Issue by uxwalter** [rpm-software-management/dnf-plugins-core#519] opened 2024-01-20 18:02 UTC
Pardon the convoluted title.

Expected behavior:
1. dnf update downloads to be updated packages, local plugin maintains a copy of downloaded package, and downloaded packages are installed on host 0
2. Subsequent "dnf update" on hosts 1-n,  after step 1 will not download updated packages but instead use copies maintained by local plugin

Actual behavior:
1. Same as step 1 above
2. Subsequent "dnf update" on hosts 1-n, when done shortly (O(minutes)) after step 1 will download updated packages again because, presumably, of cached data in /var/cache/dnf/_dnf_local*

The fact that the local plugin relies on cached repo data and therefore ignoring just downloaded updates seems to defeat the purpose of the local plugin if used to update multiple hosts at or around the same time. 
If the cache is allowed to expire, is explicitly ignored with dnf command line options, or if the cached data is explicitly deleted before subsequent updates (e.g., rm -fr /var/cache/dnf/_dnf_local*) then the local plugin behaves as expected.

**Comment by j-mracek** [comment] 2024-02-08 14:20
Thank you very much for the report.

I am not sure about several details of your use case or I am not sure whether plugin was intended for your use case.

May I ask you for a reproducer?

If the problem is related to using outdated cache after step one, I would recommend to use `--refresh` option in step 2.

**Comment by j-mracek** [comment] 2024-02-08 14:35
I've tested scenario with --refresh and it worked according to your expectations.

**Comment by j-mracek** [comment] 2024-02-12 14:38
There is an alternative workaround. Use `--setopt=_dnf_local=metadata_expire=0` in step 2.

I am closing the issue because the reported use case (using local plugin to generate cache for multiple systems) is not supported by the plugin.

**Closed by j-mracek** 2024-02-12 14:38 UTC

**Comment by uxwalter** [comment] 2024-02-13 01:54
Thanks for looking into it. I made a code change to read metadata_expire form local's .conf file and sets it without the need of command line options, if there's interest I craft a PR. 

The usage model I was describing is the same as the one documented in [Fedora Magazine](https://fedoramagazine.org/use-the-dnf-local-plugin-to-speed-up-your-home-lab/) which got me to this plugin in the first place.

**Comment by j-mracek** [comment] 2024-02-14 07:45
I believe that the default for the local repository is incorrect, therefore setting `metadata_expire=0` as a default for _dnf_local should be OK even without local's .conf file. Please feel free to provide a patch.
